# Generated by Django 3.2 on 2023-03-21 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopper',
            options={},
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='username',
        ),
    ]
