# Generated by Django 3.2 on 2023-03-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20230322_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='alias',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
