# Generated by Django 3.2 on 2023-03-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_shippingaddress_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='alias',
            field=models.CharField(blank=True, default='Alias', max_length=240),
        ),
    ]
